influxdb:
  image: influxdb:latest
  container_name: influxdb
  restart: unless-stopped
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    - influxdb:/var/lib/influxdb

telegraf:
  image: telegraf:latest
  container_name: telegraf
  restart: unless-stopped
  environment:
    - HOST_PROC=/host/proc
  links:
    - influxdb
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /proc:/host/proc:ro
    - /var/run/docker.sock:/var/run/docker.sock

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  restart: unless-stopped
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    - grafana:/var/lib/grafana
    - ./grafana_restore/etc_grafana:/etc/grafana
